import { defineConfig } from 'vitepress'
// This file is auto-generated by typedoc-vitepress-theme
import apiSidebar from '../api/typedoc-sidebar.json'

export default defineConfig({
  title: "My Vue Library",
  srcDir: 'src',
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/' },
      { text: 'API Reference', link: '/api/' }
    ],
    sidebar: {
      '/api/': apiSidebar,
      '/guide/': [
        { text: 'Getting Started', link: '/guide/' }
      ]
    }
  }
})
